/**
 * PhantomMindAI — Template Engine
 * Renders mustache-like templates with project data.
 */

const SKILLS_TEMPLATE = `# {{projectName}} — AI Skills & Context
<!-- Auto-generated by PhantomMindAI. Do not edit manually. -->
<!-- Last updated: {{timestamp}} -->

## Project Overview
- **Name**: {{projectName}}
- **Type**: {{projectType}}
- **Language**: {{primaryLanguage}}
- **Framework**: {{framework}}

## Tech Stack
{{#techStack}}
- {{.}}
{{/techStack}}

## Architecture
{{architectureDescription}}

### Directory Structure


{{directoryStructure}}


## Coding Conventions

### Naming Conventions
{{#namingConventions}}
- {{.}}
{{/namingConventions}}

### Import Patterns
{{#importPatterns}}
- {{.}}
{{/importPatterns}}

### Code Style
{{#codeStyle}}
- {{.}}
{{/codeStyle}}

## Project Patterns

### Common Patterns
{{#commonPatterns}}
- **{{name}}**: {{description}}
{{/commonPatterns}}

### Anti-Patterns (Avoid)
{{#antiPatterns}}
- ❌ {{.}}
{{/antiPatterns}}

## Key Files
{{#keyFiles}}
- \`{{path}}\` — {{description}}
{{/keyFiles}}

## Dependencies
### Production
{{#dependencies}}
- \`{{name}}\` ({{version}}) — {{description}}
{{/dependencies}}

### Dev Dependencies
{{#devDependencies}}
- \`{{name}}\` ({{version}})
{{/devDependencies}}

## Testing
- **Framework**: {{testFramework}}
- **Run**: \`{{testCommand}}\`
- **Pattern**: {{testPattern}}

## Build & Deploy
- **Build**: \`{{buildCommand}}\`
- **Dev**: \`{{devCommand}}\`
- **Deploy**: {{deployTarget}}

## Additional Context
{{additionalContext}}
`;

const RULES_TEMPLATE = `# {{projectName}} — AI Rules & Guidelines
<!-- Auto-generated by PhantomMindAI. Do not edit manually. -->
<!-- Last updated: {{timestamp}} -->

## General Rules
1. Follow the project's existing code style and conventions
2. Never hardcode secrets, API keys, or credentials
3. Always handle errors appropriately — never use empty catch blocks
4. Write self-documenting code with meaningful names
5. Keep functions focused — each function should do one thing

## Language-Specific Rules

### {{primaryLanguage}}
{{#languageRules}}
- {{.}}
{{/languageRules}}

## Framework Rules

### {{framework}}
{{#frameworkRules}}
- {{.}}
{{/frameworkRules}}

## File Organization
{{#fileOrganization}}
- {{.}}
{{/fileOrganization}}

## Import Rules
{{#importRules}}
- {{.}}
{{/importRules}}

## Testing Rules
{{#testingRules}}
- {{.}}
{{/testingRules}}

## Git Conventions
- **Branch naming**: {{branchNaming}}
- **Commit format**: {{commitFormat}}
- **PR requirements**: {{prRequirements}}

## Security Rules
1. Never commit secrets or API keys
2. Validate all user input
3. Use parameterized queries for database access
4. Sanitize output to prevent XSS
5. Follow the principle of least privilege
{{#securityRules}}
6. {{.}}
{{/securityRules}}

## Performance Rules
{{#performanceRules}}
- {{.}}
{{/performanceRules}}

## Documentation Rules
{{#documentationRules}}
- {{.}}
{{/documentationRules}}

## Forbidden Patterns
{{#forbiddenPatterns}}
- ❌ **Never**: {{.}}
{{/forbiddenPatterns}}

## Custom Rules
{{#customRules}}
- {{.}}
{{/customRules}}
`;

export interface TemplateData {
  projectName: string;
  projectType: string;
  primaryLanguage: string;
  framework: string;
  timestamp: string;
  techStack: string[];
  architectureDescription: string;
  directoryStructure: string;
  namingConventions: string[];
  importPatterns: string[];
  codeStyle: string[];
  commonPatterns: Array<{ name: string; description: string }>;
  antiPatterns: string[];
  keyFiles: Array<{ path: string; description: string }>;
  dependencies: Array<{ name: string; version: string; description: string }>;
  devDependencies: Array<{ name: string; version: string }>;
  testFramework: string;
  testCommand: string;
  testPattern: string;
  buildCommand: string;
  devCommand: string;
  deployTarget: string;
  additionalContext: string;
  // RULES template extras
  languageRules: string[];
  frameworkRules: string[];
  fileOrganization: string[];
  importRules: string[];
  testingRules: string[];
  branchNaming: string;
  commitFormat: string;
  prRequirements: string;
  securityRules: string[];
  performanceRules: string[];
  documentationRules: string[];
  forbiddenPatterns: string[];
  customRules: string[];
}

export class TemplateEngine {
  /**
   * Render a template with data
   */
  static render(template: string, data: Partial<TemplateData>): string {
    let result = template;

    // Handle array sections {{#key}}...{{/key}}
    result = result.replace(
      /\{\{#(\w+)\}\}([\s\S]*?)\{\{\/\1\}\}/g,
      (_, key, content) => {
        const value = (data as any)[key];
        if (!value) return '';

        if (Array.isArray(value)) {
          return value.map(item => {
            if (typeof item === 'string') {
              return content.replace(/\{\{\.\}\}/g, item);
            }
            if (typeof item === 'object') {
              let rendered = content;
              for (const [k, v] of Object.entries(item)) {
                rendered = rendered.replace(
                  new RegExp(`\\{\\{${k}\\}\\}`, 'g'),
                  String(v),
                );
              }
              return rendered;
            }
            return content;
          }).join('');
        }

        return value ? content : '';
      },
    );

    // Handle simple variables {{key}}
    result = result.replace(/\{\{(\w+)\}\}/g, (_, key) => {
      const value = (data as any)[key];
      if (value === undefined || value === null) return '';
      return String(value);
    });

    // Clean up empty lines from removed sections
    result = result.replace(/\n{3,}/g, '\n\n');

    return result;
  }

  /**
   * Load and render the SKILLS template
   */
  static async renderSkills(data: Partial<TemplateData>): Promise<string> {
    return this.render(SKILLS_TEMPLATE, {
      ...data,
      timestamp: new Date().toISOString(),
    });
  }

  /**
   * Load and render the RULES template
   */
  static async renderRules(data: Partial<TemplateData>): Promise<string> {
    return this.render(RULES_TEMPLATE, {
      ...data,
      timestamp: new Date().toISOString(),
    });
  }
}
