import { describe, it, expect } from 'vitest';
import { CopilotAdapter } from './copilot.js';
import { CursorAdapter } from './cursor.js';
import { ClineAdapter } from './cline.js';
import { WindsurfAdapter } from './windsurf.js';

describe('Adapters', () => {
  const skills = '## Architecture\nMVVM pattern with dependency injection';
  const rules = '## Rules\n- Always use TypeScript strict mode\n- No any types';
  const schema = '{"type":"object","properties":{"status":{"type":"string"}}}';

  describe('CopilotAdapter', () => {
    const adapter = new CopilotAdapter();

    it('has correct name and output path', () => {
      expect(adapter.name).toBe('copilot');
      expect(adapter.outputPath).toBe('.github/copilot-instructions.md');
      expect(adapter.format).toBe('markdown');
    });

    it('generates content with skills section', () => {
      const content = adapter.generate(skills, rules, schema);
      expect(content).toContain('Project Knowledge');
      expect(content).toContain('MVVM pattern');
    });

    it('generates content with rules section', () => {
      const content = adapter.generate(skills, rules, schema);
      expect(content).toContain('Rules & Constraints');
      expect(content).toContain('TypeScript strict mode');
    });

    it('generates content with schema section', () => {
      const content = adapter.generate(skills, rules, schema);
      expect(content).toContain('Output Schemas');
      expect(content).toContain('```json');
    });

    it('includes auto-generated header', () => {
      const content = adapter.generate(skills, rules, schema);
      expect(content).toContain('AUTO-GENERATED BY PHANTOMIND');
      expect(content).toContain('Do not edit this file directly');
    });

    it('handles empty inputs gracefully', () => {
      const content = adapter.generate('', '', '');
      expect(content).toContain('AUTO-GENERATED');
      expect(content).not.toContain('Project Knowledge');
    });
  });

  describe('CursorAdapter', () => {
    const adapter = new CursorAdapter();

    it('has correct name and output path', () => {
      expect(adapter.name).toBe('cursor');
      expect(adapter.outputPath).toBe('.cursorrules');
      expect(adapter.format).toBe('text');
    });

    it('generates content with all sections', () => {
      const content = adapter.generate(skills, rules, schema);
      expect(content).toContain('MVVM pattern');
      expect(content).toContain('TypeScript strict mode');
    });
  });

  describe('ClineAdapter', () => {
    const adapter = new ClineAdapter();

    it('has correct name and output path', () => {
      expect(adapter.name).toBe('cline');
      expect(adapter.outputPath).toBe('.clinerules');
    });

    it('generates valid content', () => {
      const content = adapter.generate(skills, rules, schema);
      expect(content.length).toBeGreaterThan(0);
      expect(content).toContain('MVVM pattern');
    });
  });

  describe('WindsurfAdapter', () => {
    const adapter = new WindsurfAdapter();

    it('has correct name and output path', () => {
      expect(adapter.name).toBe('windsurf');
      expect(adapter.outputPath).toBe('.windsurfrules');
    });

    it('generates valid content', () => {
      const content = adapter.generate(skills, rules, schema);
      expect(content.length).toBeGreaterThan(0);
    });
  });
});
